"use client";

import { use, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { authenticatedFetch } from "@/lib/auth/client";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { toast } from "sonner";

// --- Types ---
type RecipeRow = {
  id: string;
  productId: string;
  ingredientId: string;
  unitId: string;
  quantityPerProduct: number;
  wastagePercent: number;
  notes: string | null;
  productName: string;
  ingredientName: string;
  unitCode: string;
};

type RecipeOptions = {
  products: Array<{ id: string; name: string }>;
  ingredients: Array<{
    id: string;
    name: string;
    units: Array<{ unitId: string; unitCode: string }>;
  }>;
};

// --- Shared Styles ---
const inputCls =
  "bg-card border border-border rounded-lg px-3 py-2 text-sm w-full focus:outline-none focus:ring-2 focus:ring-accent/40 focus:border-accent transition-colors";
const selectCls =
  "bg-card border border-border rounded-lg px-3 py-2 text-sm w-full focus:outline-none focus:ring-2 focus:ring-accent/40 focus:border-accent transition-colors appearance-none";
const labelCls =
  "block text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-1";

// --- Main Page Component ---
export default function ProductRecipePage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = use(params);

  const [recipes, setRecipes] = useState<RecipeRow[]>([]);
  const [options, setOptions] = useState<RecipeOptions>({ products: [], ingredients: [] });
  const [isLoading, setIsLoading] = useState(true);
  const [form, setForm] = useState({
    ingredientId: "",
    unitId: "",
    quantityPerProduct: "",
    wastagePercent: "0",
    notes: "",
  });

  /* 
   * Resolve the product ID from the slug by matching the slug format.
   * The slug is generated by lowercasing the name, replacing spaces with hyphens, and removing special characters.
   */
  const product = useMemo(
    () => options.products.find((p) => p.name.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "") === slug),
    [options.products, slug]
  );

  const productId = product?.id ?? null;

  /* Recipes filtered for this product */
  const productRecipes = useMemo(
    () => recipes.filter((r) => r.productId === productId),
    [recipes, productId]
  );

  /* Load everything from the API */
  const loadData = useCallback(async () => {
    try {
      setIsLoading(true);
      const response = await authenticatedFetch("/api/admin/recipes");
      const payload = await response.json();
      if (response.ok && payload.success) {
        setRecipes(payload.data);
        setOptions(payload.options);
      }
    } catch {
      toast.error("Gagal memuat recipe");
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    loadData();
  }, [loadData]);

  /* Auto-select first ingredient when options load */
  useEffect(() => {
    if (!form.ingredientId && options.ingredients.length > 0) {
      const first = options.ingredients[0];
      setForm((prev) => ({
        ...prev,
        ingredientId: first.id,
        unitId: first.units[0]?.unitId ?? "",
      }));
    }
  }, [form.ingredientId, options.ingredients]);

  /* Reset unitId when ingredient changes */
  const selectedIngredientUnits = useMemo(
    () => options.ingredients.find((i) => i.id === form.ingredientId)?.units ?? [],
    [options.ingredients, form.ingredientId]
  );

  useEffect(() => {
    if (
      selectedIngredientUnits.length > 0 &&
      !selectedIngredientUnits.some((u) => u.unitId === form.unitId)
    ) {
      setForm((prev) => ({ ...prev, unitId: selectedIngredientUnits[0].unitId }));
    }
  }, [form.ingredientId, form.unitId, selectedIngredientUnits]);

  // --- Handlers ---
  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!productId) {
      toast.error("Produk tidak ditemukan");
      return;
    }
    const quantityPerProduct = Number(form.quantityPerProduct);
    const wastagePercent = Number(form.wastagePercent || 0);

    if (!form.ingredientId || !form.unitId || quantityPerProduct <= 0) {
      toast.error("Lengkapi form recipe");
      return;
    }

    try {
      const response = await authenticatedFetch("/api/admin/recipes", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          productId,
          ingredientId: form.ingredientId,
          unitId: form.unitId,
          quantityPerProduct,
          wastagePercent,
          notes: form.notes,
        }),
      });

      const payload = await response.json();
      if (!response.ok || !payload.success) throw new Error();

      toast.success("Recipe berhasil disimpan");
      setForm((prev) => ({ ...prev, quantityPerProduct: "", wastagePercent: "0", notes: "" }));
      await loadData();
    } catch {
      toast.error("Gagal menyimpan recipe");
    }
  };

  const handleDelete = async (id: string) => {
    try {
      const response = await authenticatedFetch("/api/admin/recipes", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id }),
      });
      const payload = await response.json();
      if (!response.ok || !payload.success) throw new Error();
      setRecipes((prev) => prev.filter((item) => item.id !== id));
      toast.success("Recipe dihapus");
    } catch {
      toast.error("Gagal menghapus recipe");
    }
  };

  // --- Render ---
  return (
    <section className="w-full max-w-7xl mx-auto px-4 sm:px-6 md:px-8 pt-12 pb-8 space-y-6">
      {/* Back link */}
      <Link
        href="/admin/products"
        className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-accent transition-colors"
      >
        <span aria-hidden="true">←</span>
        Kembali ke Produk
      </Link>

      {/* Page Header */}
      <div>
        <h1 className="text-3xl font-semibold text-primary">
          {isLoading ? (
            <span className="inline-block h-8 w-48 bg-muted/40 rounded animate-pulse" />
          ) : product ? (
            <>Recipe: {product.name}</>
          ) : (
            "Produk tidak ditemukan"
          )}
        </h1>
        <p className="text-sm text-muted-foreground mt-1">
          Atur komposisi bahan untuk produk ini.
        </p>
      </div>

      {/* Add Recipe Form */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base font-semibold text-primary">
            Tambah Bahan ke Recipe
          </CardTitle>
        </CardHeader>
        <CardContent>
          <form
            onSubmit={handleSubmit}
            className="grid sm:grid-cols-2 lg:grid-cols-6 gap-4 items-end"
          >
            {/* Ingredient */}
            <div className="sm:col-span-2">
              <label className={labelCls}>Ingredient</label>
              <div className="relative">
                <select
                  className={selectCls}
                  value={form.ingredientId}
                  onChange={(event) =>
                    setForm((prev) => ({ ...prev, ingredientId: event.target.value }))
                  }
                  required
                >
                  {options.ingredients.map((ingredient) => (
                    <option key={ingredient.id} value={ingredient.id}>
                      {ingredient.name}
                    </option>
                  ))}
                </select>
                <span className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground text-xs">
                  ▾
                </span>
              </div>
            </div>

            {/* Unit */}
            <div>
              <label className={labelCls}>Satuan</label>
              <div className="relative">
                <select
                  className={selectCls}
                  value={form.unitId}
                  onChange={(event) =>
                    setForm((prev) => ({ ...prev, unitId: event.target.value }))
                  }
                  required
                >
                  {selectedIngredientUnits.map((unit) => (
                    <option key={unit.unitId} value={unit.unitId}>
                      {unit.unitCode}
                    </option>
                  ))}
                </select>
                <span className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground text-xs">
                  ▾
                </span>
              </div>
            </div>

            {/* Qty per product */}
            <div>
              <label className={labelCls}>Qty / Produk</label>
              <Input
                className={inputCls}
                type="number"
                min={0.0001}
                step="0.0001"
                value={form.quantityPerProduct}
                onChange={(event) =>
                  setForm((prev) => ({ ...prev, quantityPerProduct: event.target.value }))
                }
                placeholder="cth: 250"
                required
              />
            </div>

            {/* Wastage % */}
            <div>
              <label className={labelCls}>Wastage (%)</label>
              <Input
                className={inputCls}
                type="number"
                min={0}
                step="0.01"
                value={form.wastagePercent}
                onChange={(event) =>
                  setForm((prev) => ({ ...prev, wastagePercent: event.target.value }))
                }
                placeholder="cth: 5"
              />
            </div>

            {/* Submit */}
            <Button type="submit" className="w-full">
              Tambah
            </Button>

            {/* Notes – full row */}
            <div className="sm:col-span-2 lg:col-span-6">
              <label className={labelCls}>Catatan</label>
              <Input
                className={inputCls}
                value={form.notes}
                onChange={(event) =>
                  setForm((prev) => ({ ...prev, notes: event.target.value }))
                }
                placeholder="Opsional"
              />
            </div>
          </form>
        </CardContent>
      </Card>

      {/* Recipe Table */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base font-semibold text-primary">
            Daftar Bahan Recipe
          </CardTitle>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="flex items-center gap-2 text-sm text-muted-foreground py-4">
              <span className="size-4 border-2 border-accent border-t-transparent rounded-full animate-spin" />
              Memuat data…
            </div>
          ) : productRecipes.length === 0 ? (
            <p className="text-sm text-muted-foreground py-4">
              Belum ada bahan dalam recipe ini. Tambahkan menggunakan form di atas.
            </p>
          ) : (
            <div className="overflow-x-auto -mx-1">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-muted/40">
                    <th className="text-left px-3 py-2.5 text-xs font-semibold uppercase tracking-wider text-muted-foreground rounded-tl-lg">
                      Ingredient
                    </th>
                    <th className="text-left px-3 py-2.5 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                      Qty / Produk
                    </th>
                    <th className="text-left px-3 py-2.5 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                      Satuan
                    </th>
                    <th className="text-left px-3 py-2.5 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                      Wastage (%)
                    </th>
                    <th className="text-left px-3 py-2.5 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                      Catatan
                    </th>
                    <th className="text-right px-3 py-2.5 text-xs font-semibold uppercase tracking-wider text-muted-foreground rounded-tr-lg">
                      Aksi
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {productRecipes.map((recipe) => (
                    <tr
                      key={recipe.id}
                      className="bg-background hover:bg-muted/10 transition-colors"
                    >
                      <td className="px-3 py-3 font-medium text-foreground">
                        {recipe.ingredientName}
                      </td>
                      <td className="px-3 py-3 tabular-nums text-foreground">
                        {recipe.quantityPerProduct}
                      </td>
                      <td className="px-3 py-3 text-muted-foreground">
                        {recipe.unitCode}
                      </td>
                      <td className="px-3 py-3">
                        {recipe.wastagePercent > 0 ? (
                          <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs bg-yellow-50 text-yellow-700 border border-yellow-200">
                            {recipe.wastagePercent}%
                          </span>
                        ) : (
                          <span className="text-muted-foreground text-xs">—</span>
                        )}
                      </td>
                      <td className="px-3 py-3 text-muted-foreground text-xs max-w-40 truncate">
                        {recipe.notes || (
                          <span className="italic text-border">tidak ada</span>
                        )}
                      </td>
                      <td className="px-3 py-3 text-right">
                        <AlertDialog>
                          <AlertDialogTrigger asChild>
                            <Button size="sm" variant="destructive">
                              Hapus
                            </Button>
                          </AlertDialogTrigger>
                          <AlertDialogContent>
                            <AlertDialogHeader>
                              <AlertDialogTitle>Hapus Recipe?</AlertDialogTitle>
                              <AlertDialogDescription>
                                Baris recipe ini akan dihapus permanen. Aksi ini tidak dapat dibatalkan.
                              </AlertDialogDescription>
                            </AlertDialogHeader>
                            <AlertDialogFooter>
                              <AlertDialogCancel>Batal</AlertDialogCancel>
                              <AlertDialogAction onClick={() => handleDelete(recipe.id)} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">
                                Hapus
                              </AlertDialogAction>
                            </AlertDialogFooter>
                          </AlertDialogContent>
                        </AlertDialog>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>
    </section>
  );
}
